name: Create sandbox promotion pull request
on:
  push:
    branches:
      - main
jobs:
  sandboxPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: sandbox
      - name: Reset sandbox branch
        run: |
          git fetch origin main:main
          echo "DIFF=$(git log --pretty='%h %s %aN' sandbox..main)" >> "$GITHUB_ENV"
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: sandbox-promotion
          commit-message: Release to Sandbox ${{ github.event.repository.updated_at}}
          title: Release to Sandbox ${{ github.event.repository.updated_at}}
          body: ${{env.DIFF}}