name: Create sandbox promotion pull request
on:
  push:
    branches:
      - main
jobs:
  sandboxPromotion:
    uses: ./.github/workflows/reusable-pull-request.yml
    with:
      base-branch: sandbox
      compare-branch: main