name: Act on set schedule
on:
  schedule:
    - cron: '0/10 22-23 * * 4'
jobs:
  Prep-Prod-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trivial pass
        run: |
            echo "::notice This would be the open PR action"
            exit 0