name: Act on merge to named branch
on:
  push:
    branches:
      - production
jobs:
  Deploy-Staging:
    runs-on: ubuntu-latest
    steps:
      - name: Trivial pass
        run: |
            echo "::notice This would be the deploy action"
            exit 0