name: fast-forward
on:
  pull_request_review:
    types: [submitted]
jobs:
  fast-forward:
    # Only run if the comment contains the /fast-forward command.
    if: ${{ contains(github.event.pull_request.base.label, 'sandbox') && github.event.review.state =='approved'}}
    runs-on: ubuntu-latest

    steps:
      - name: Log branch base name
        run:
          echo ${{github.event.review.body}}
      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@v1
        with:
          github_token: ${{secrets.TESTING_PAT}}
          merge: true
          # To reduce the workflow's verbosity, use 'on-error'
          # to only post a comment when an error occurs, or 'never' to
          # never post a comment.  (In all cases the information is
          # still available in the step's summary.)
          comment: always