name: Create pull request on branch push
on:
  workflow_call:
    inputs:
      base-branch:
        required: true
        type: string
      compare-branch:
        required: true
        type: string
jobs:
  sync-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{inputs.base-branch}}
      - name: Fetch ${{inputs.compare-branch}}
        run: git fetch origin ${{inputs.compare-branch}}:${{inputs.compare-branch}}
      - name: Get title data
        run: |
          echo "FIRST_COMMIT=$(git log ${{inputs.base-branch}}..${{inputs.compare-branch}} --pretty=%h  --reverse | head -1)" >> "$GITHUB_ENV"
          echo "LAST_COMMIT=$(git log ${{inputs.base-branch}}..${{inputs.compare-branch}} --pretty=%h | head -1)" >> "$GITHUB_ENV"
          {
            echo 'DIFF<<EOF'
            git log --pretty='%h %s %aN' ${{inputs.base-branch}}..${{inputs.compare-branch}}
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Reset ${{inputs.base-branch}} branch
        run: git reset --hard ${{inputs.compare-branch}}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{inputs.base-branch}}-promotion
          title: Release to ${{inputs.base-branch}} ${{ env.FIRST_COMMIT}} - ${{env.LAST_COMMIT}}
          body: ${{env.DIFF}}