name: Create production promotion pull request
on:
  workflow_run:
    workflows: "fast-forward"
    types:
      - completed
    branches:
      - sandbox
jobs:
  getReleaseTime:
    runs-on: ubuntu-latest
    outputs:
      title: ${{steps.title.outputs.time}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Get deploy time
        id: title
        uses: ./.github/actions/release-time/
      - name: Print time
        run: echo Next deploy at ${{steps.title.outputs.time}}
  productionPullRequest:
      needs: getReleaseTime
      uses: ./.github/workflows/reusable-pull-request.yml
      with:
        base-branch: production
        compare-branch: sandbox
        title: ${{needs.getReleaseTime.outputs.title}}