name: Create sandbox promotion pull request
on:
  push:
    branches:
      - sandbox
jobs:
  sandboxPromotion:
    uses: ./.github/workflows/reusable-pull-request.yml
    with:
      base-branch: production
      compare-branch: sandbox